# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created: Fri Dec 29 09:19:39 2017
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(647, 457)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        #MainWindow.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(647, 457))
        MainWindow.setMaximumSize(QtCore.QSize(647, 457))
        #coros logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/coros_Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.weloop_daily_data = QtGui.QPushButton(self.centralwidget)
        self.weloop_daily_data.setGeometry(QtCore.QRect(30, 90, 75, 51))
        self.weloop_daily_data.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.weloop_daily_data.setObjectName(_fromUtf8("weloop_daily_data"))
        # coros logo设计图标设计
        weloop_daily_data = QtGui.QIcon()
        weloop_daily_data.addPixmap(QtGui.QPixmap(_fromUtf8("./img/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weloop_daily_data.setIcon(weloop_daily_data)
        self.weloop_daily_data.setIconSize(QtCore.QSize(71, 71))
        self.weloop_daily_data.setStyleSheet("background:transparent")
        self.label_daily = QtGui.QLabel(self.centralwidget)
        self.label_daily.setGeometry(QtCore.QRect(40, 130, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_daily.setFont(font)
        self.label_daily.setText(QtGui.QApplication.translate("MainWindow", "日常数据", None, QtGui.QApplication.UnicodeUTF8))
        self.label_daily.setObjectName(_fromUtf8("label_daily"))
        self.label_daily.setStyleSheet("color:white")
        #户外跑步设计
        self.weloop_outdoor = QtGui.QPushButton(self.centralwidget)
        self.weloop_outdoor.setGeometry(QtCore.QRect(180, 90, 75, 51))
        self.weloop_outdoor.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.weloop_outdoor.setObjectName(_fromUtf8("weloop_outdoor"))
        #户外跑步图标设计
        icon_weloop_out_door = QtGui.QIcon()
        icon_weloop_out_door.addPixmap(QtGui.QPixmap(_fromUtf8("./img/outdoor run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weloop_outdoor.setIcon(icon_weloop_out_door)
        self.weloop_outdoor.setIconSize(QtCore.QSize(71, 71))
        self.weloop_outdoor.setStyleSheet("background:transparent")
        self.label_outdoor = QtGui.QLabel(self.centralwidget)
        self.label_outdoor.setGeometry(QtCore.QRect(180, 130, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_outdoor.setFont(font)
        self.label_outdoor.setText(QtGui.QApplication.translate("MainWindow", "户外跑步", None, QtGui.QApplication.UnicodeUTF8))
        self.label_outdoor.setObjectName(_fromUtf8("label_outdoor"))
        self.label_outdoor.setStyleSheet("color:white")
        #骑行设计
        self.weloop_cycle = QtGui.QPushButton(self.centralwidget)
        self.weloop_cycle.setGeometry(QtCore.QRect(320, 90, 75, 51))
        self.weloop_cycle.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.weloop_cycle.setObjectName(_fromUtf8("weloop_cycle"))
        #骑行图标设计
        icon_weloop_cycle = QtGui.QIcon()
        icon_weloop_cycle.addPixmap(QtGui.QPixmap(_fromUtf8("./img/cycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weloop_cycle.setIcon(icon_weloop_cycle)
        self.weloop_cycle.setIconSize(QtCore.QSize(71, 71))
        self.weloop_cycle.setStyleSheet("background:transparent")
        self.label_cycle = QtGui.QLabel(self.centralwidget)
        self.label_cycle.setGeometry(QtCore.QRect(340, 130, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_cycle.setFont(font)
        self.label_cycle.setText(QtGui.QApplication.translate("MainWindow", "骑行", None, QtGui.QApplication.UnicodeUTF8))
        self.label_cycle.setObjectName(_fromUtf8("label_cycle"))
        self.label_cycle.setStyleSheet("color:white")
        #游泳设计
        self.weloop_swim = QtGui.QPushButton(self.centralwidget)
        self.weloop_swim.setGeometry(QtCore.QRect(450, 90, 75, 51))
        self.weloop_swim.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.weloop_swim.setObjectName(_fromUtf8("weloop_swim"))
        # 游泳图标设计
        weloop_swim = QtGui.QIcon()
        weloop_swim.addPixmap(QtGui.QPixmap(_fromUtf8("./img/pool swim.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weloop_swim.setIcon(weloop_swim)
        self.weloop_swim.setIconSize(QtCore.QSize(71, 71))
        self.weloop_swim.setStyleSheet("background:transparent")
        self.label_swim = QtGui.QLabel(self.centralwidget)
        self.label_swim.setGeometry(QtCore.QRect(460, 130, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_swim.setFont(font)
        self.label_swim.setText(QtGui.QApplication.translate("MainWindow", "泳池游泳", None, QtGui.QApplication.UnicodeUTF8))
        self.label_swim.setObjectName(_fromUtf8("label_swim"))
        self.label_swim.setStyleSheet("color:white")

        #weloop图标设计
        self.weloop = QtGui.QPushButton(self.centralwidget)
        self.weloop.setGeometry(QtCore.QRect(250, 10, 75, 51))
        self.weloop.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.weloop.setObjectName(_fromUtf8("weloop"))
        icon_weloop = QtGui.QIcon()
        icon_weloop.addPixmap(QtGui.QPixmap(_fromUtf8("./img/weloop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weloop.setIcon(icon_weloop)
        self.weloop.setIconSize(QtCore.QSize(71, 71))
        self.weloop.setObjectName(_fromUtf8("pushButton"))
        self.weloop.setStyleSheet("background:transparent")
        self.label_weloop = QtGui.QLabel(self.centralwidget)
        self.label_weloop.setGeometry(QtCore.QRect(250, 50, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_weloop.setFont(font)
        self.label_weloop.setText(QtGui.QApplication.translate("MainWindow", "WeLoop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_weloop.setObjectName(_fromUtf8("label_weloop"))
        self.label_weloop.setStyleSheet("color:white")




        self.coros = QtGui.QPushButton(self.centralwidget)
        self.coros.setGeometry(QtCore.QRect(250, 200, 100, 80))
        self.coros.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros.setObjectName(_fromUtf8("coros"))
        icon_coros = QtGui.QIcon()
        icon_coros.addPixmap(QtGui.QPixmap(_fromUtf8("./img/coros_Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros.setIcon(icon_coros)
        self.coros.setIconSize(QtCore.QSize(100, 100))
        self.coros.setObjectName(_fromUtf8("pushButton"))
        self.coros.setStyleSheet("background:transparent")



        self.coros_Triathlon = QtGui.QPushButton(self.centralwidget)
        self.coros_Triathlon.setGeometry(QtCore.QRect(30, 287, 75, 51))
        self.coros_Triathlon.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros_Triathlon.setObjectName(_fromUtf8("coros_Triathlon"))
        # 图标设计
        coros_Triathlon = QtGui.QIcon()
        coros_Triathlon.addPixmap(QtGui.QPixmap(_fromUtf8("./img/Triathlon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros_Triathlon.setIcon(coros_Triathlon)
        self.coros_Triathlon.setIconSize(QtCore.QSize(71, 71))
        self.coros_Triathlon.setStyleSheet("background:transparent")
        self.label_coros_Triathlon = QtGui.QLabel(self.centralwidget)
        self.label_coros_Triathlon.setGeometry(QtCore.QRect(40, 330, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_coros_Triathlon.setFont(font)
        self.label_coros_Triathlon.setText(
            QtGui.QApplication.translate("MainWindow", "铁人三项", None, QtGui.QApplication.UnicodeUTF8))
        self.label_coros_Triathlon.setObjectName(_fromUtf8("label_coros_Triathlon"))
        self.label_coros_Triathlon.setStyleSheet("color:white")

        self.coros_outdoor = QtGui.QPushButton(self.centralwidget)
        self.coros_outdoor.setGeometry(QtCore.QRect(160, 290, 75, 51))
        self.coros_outdoor.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros_outdoor.setObjectName(_fromUtf8("coros_outdoor"))
        # 图标设计
        coros_outdoor = QtGui.QIcon()
        coros_outdoor.addPixmap(QtGui.QPixmap(_fromUtf8("./img/outdoor run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros_outdoor.setIcon(coros_outdoor)
        self.coros_outdoor.setIconSize(QtCore.QSize(71, 71))
        self.coros_outdoor.setStyleSheet("background:transparent")
        self.label_coros_outdoor = QtGui.QLabel(self.centralwidget)
        self.label_coros_outdoor.setGeometry(QtCore.QRect(160, 330, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_coros_outdoor.setFont(font)
        self.label_coros_outdoor.setText(
            QtGui.QApplication.translate("MainWindow", "户外跑步", None, QtGui.QApplication.UnicodeUTF8))
        self.label_coros_outdoor.setObjectName(_fromUtf8("label_coros_outdoor"))
        self.label_coros_outdoor.setStyleSheet("color:white")

        self.coros_cycle = QtGui.QPushButton(self.centralwidget)
        self.coros_cycle.setGeometry(QtCore.QRect(270, 290, 75, 51))
        self.coros_cycle.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros_cycle.setObjectName(_fromUtf8("coros_cycle"))
        # 图标设计
        coros_cycle = QtGui.QIcon()
        coros_cycle.addPixmap(QtGui.QPixmap(_fromUtf8("./img/cycle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros_cycle.setIcon(coros_cycle)
        self.coros_cycle.setIconSize(QtCore.QSize(71, 71))
        self.coros_cycle.setStyleSheet("background:transparent")
        self.label_coros_cycle = QtGui.QLabel(self.centralwidget)
        self.label_coros_cycle.setGeometry(QtCore.QRect(290, 330, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_coros_cycle.setFont(font)
        self.label_coros_cycle.setText(
            QtGui.QApplication.translate("MainWindow", "骑行", None, QtGui.QApplication.UnicodeUTF8))
        self.label_coros_cycle.setObjectName(_fromUtf8("label_coros_cycle"))
        self.label_coros_cycle.setStyleSheet("color:white")

        self.coros_swim = QtGui.QPushButton(self.centralwidget)
        self.coros_swim.setGeometry(QtCore.QRect(390, 290, 75, 51))
        self.coros_swim.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros_swim.setObjectName(_fromUtf8("coros_swim"))
        # 图标设计
        coros_swim = QtGui.QIcon()
        coros_swim.addPixmap(QtGui.QPixmap(_fromUtf8("./img/pool swim.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros_swim.setIcon(coros_swim)
        self.coros_swim.setIconSize(QtCore.QSize(71, 71))
        self.coros_swim.setStyleSheet("background:transparent")
        self.label_coros_swim = QtGui.QLabel(self.centralwidget)
        self.label_coros_swim.setGeometry(QtCore.QRect(400, 330, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_coros_swim.setFont(font)
        self.label_coros_swim.setText(
            QtGui.QApplication.translate("MainWindow", "泳池游泳", None, QtGui.QApplication.UnicodeUTF8))
        self.label_coros_swim.setObjectName(_fromUtf8("label_coros_swim"))
        self.label_coros_swim.setStyleSheet("color:white")

        self.coros_open_swim = QtGui.QPushButton(self.centralwidget)
        self.coros_open_swim.setGeometry(QtCore.QRect(530, 285, 75, 51))
        self.coros_open_swim.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.coros_open_swim.setObjectName(_fromUtf8("coros_open_swim"))
        # 图标设计
        coros_open_swim = QtGui.QIcon()
        coros_open_swim.addPixmap(QtGui.QPixmap(_fromUtf8("./img/open water.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coros_open_swim.setIcon(coros_open_swim)
        self.coros_open_swim.setIconSize(QtCore.QSize(71, 71))
        self.coros_open_swim.setStyleSheet("background:transparent")
        self.label_coros_open_swim = QtGui.QLabel(self.centralwidget)
        self.label_coros_open_swim.setGeometry(QtCore.QRect(540, 330, 80, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(120)
        self.label_coros_open_swim.setFont(font)
        self.label_coros_open_swim.setText(
            QtGui.QApplication.translate("MainWindow", "公开水域", None, QtGui.QApplication.UnicodeUTF8))
        self.label_coros_open_swim.setObjectName(_fromUtf8("label_coros_open_swim"))
        self.label_coros_open_swim.setStyleSheet("color:white")

        #MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
       # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

