# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sport_ui.ui'
#
# Created: Thu Dec 28 16:49:35 2017
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(724, 533)
        Form.setMinimumSize(QtCore.QSize(724, 533))
        Form.setMaximumSize(QtCore.QSize(724, 533))
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        #weloop logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/weloop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        self.time_zone_2 = QtGui.QLabel(Form)
        self.time_zone_2.setGeometry(QtCore.QRect(320, 60, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.time_zone_2.setFont(font)
        self.time_zone_2.setText(QtGui.QApplication.translate("Form", "时区", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone_2.setObjectName(_fromUtf8("time_zone_2"))
        self.time_zone = QtGui.QLineEdit(Form)
        self.time_zone.setGeometry(QtCore.QRect(360, 60, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.time_zone.setFont(font)
        self.time_zone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_zone.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.time_zone.setObjectName(_fromUtf8("time_zone"))
        self.end_time = QtGui.QLineEdit(Form)
        self.end_time.setGeometry(QtCore.QRect(480, 60, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.end_time.setFont(font)
        self.end_time.setText(QtGui.QApplication.translate("Form", "2017/12/13 00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.end_time.setObjectName(_fromUtf8("end_time"))
        self.start_time_2 = QtGui.QLabel(Form)
        self.start_time_2.setGeometry(QtCore.QRect(43, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_2.setFont(font)
        self.start_time_2.setText(QtGui.QApplication.translate("Form", "开始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_2.setObjectName(_fromUtf8("start_time_2"))
        self.start_time = QtGui.QDateTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(110, 60, 194, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time.setFont(font)
        self.start_time.setDate(QtCore.QDate(2017, 12, 13))
        self.start_time.setTime(QtCore.QTime(10, 0, 0))
        self.start_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.start_time.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.start_time.setMinimumTime(QtCore.QTime(10, 0, 0))
        self.start_time.setObjectName(_fromUtf8("start_time"))
        self.title = QtGui.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(270, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setText(QtGui.QApplication.translate("Form", "数据格式设定", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setObjectName(_fromUtf8("title"))
        self.end_time_2 = QtGui.QLabel(Form)
        self.end_time_2.setGeometry(QtCore.QRect(420, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.end_time_2.setFont(font)
        self.end_time_2.setText(QtGui.QApplication.translate("Form", "结束时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.end_time_2.setObjectName(_fromUtf8("end_time_2"))
        self.locus_box = QtGui.QComboBox(Form)
        self.locus_box.setGeometry(QtCore.QRect(150, 100, 69, 22))
        self.locus_box.setObjectName(_fromUtf8("locus_box"))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(0, QtGui.QApplication.translate("Form", "东莞", None, QtGui.QApplication.UnicodeUTF8))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(1, QtGui.QApplication.translate("Form", "深圳", None, QtGui.QApplication.UnicodeUTF8))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(2, QtGui.QApplication.translate("Form", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.locus = QtGui.QLabel(Form)
        self.locus.setGeometry(QtCore.QRect(90, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.locus.setFont(font)
        self.locus.setText(QtGui.QApplication.translate("Form", "轨迹区域", None, QtGui.QApplication.UnicodeUTF8))
        self.locus.setObjectName(_fromUtf8("locus"))
        self.sport_time = QtGui.QLabel(Form)
        self.sport_time.setGeometry(QtCore.QRect(90, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time.setFont(font)
        self.sport_time.setText(QtGui.QApplication.translate("Form", "运动时长", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time.setObjectName(_fromUtf8("sport_time"))
        self.sport_time_set = QtGui.QLineEdit(Form)
        self.sport_time_set.setGeometry(QtCore.QRect(150, 140, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_set.setFont(font)
        self.sport_time_set.setText(QtGui.QApplication.translate("Form", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_set.setAlignment(QtCore.Qt.AlignCenter)
        self.sport_time_set.setObjectName(_fromUtf8("sport_time_set"))
        self.sport_time_2 = QtGui.QLabel(Form)
        self.sport_time_2.setGeometry(QtCore.QRect(230, 140, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.sport_time_2.setFont(font)
        self.sport_time_2.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_2.setObjectName(_fromUtf8("sport_time_2"))
        self.graphicsView = QtGui.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 230, 721, 301))
        self.graphicsView.setMinimumSize(QtCore.QSize(721, 0))
        self.graphicsView.setMaximumSize(QtCore.QSize(721, 301))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.commit = QtGui.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(90, 180, 61, 31))
        self.commit.setText(QtGui.QApplication.translate("Form", "确认", None, QtGui.QApplication.UnicodeUTF8))
        self.commit.setObjectName(_fromUtf8("commit"))
        self.verify = QtGui.QPushButton(Form)
        self.verify.setGeometry(QtCore.QRect(180, 180, 61, 31))
        self.verify.setText(QtGui.QApplication.translate("Form", "验证", None, QtGui.QApplication.UnicodeUTF8))
        self.verify.setObjectName(_fromUtf8("verify"))
        self.data_choice = QtGui.QLabel(Form)
        self.data_choice.setGeometry(QtCore.QRect(450, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.data_choice.setFont(font)
        self.data_choice.setText(QtGui.QApplication.translate("Form", "数据选项", None, QtGui.QApplication.UnicodeUTF8))
        self.data_choice.setObjectName(_fromUtf8("data_choice"))
        self.heart = QtGui.QCheckBox(Form)
        self.heart.setGeometry(QtCore.QRect(410, 140, 71, 16))
        self.heart.setText(QtGui.QApplication.translate("Form", "心率", None, QtGui.QApplication.UnicodeUTF8))
        self.heart.setChecked(True)
        self.heart.setObjectName(_fromUtf8("heart"))
        self.cadence = QtGui.QCheckBox(Form)
        self.cadence.setGeometry(QtCore.QRect(410, 160, 71, 16))
        self.cadence.setText(QtGui.QApplication.translate("Form", "步频", None, QtGui.QApplication.UnicodeUTF8))
        self.cadence.setChecked(False)
        self.cadence.setObjectName(_fromUtf8("cadence"))
        self.pace = QtGui.QCheckBox(Form)
        self.pace.setGeometry(QtCore.QRect(410, 180, 71, 16))
        self.pace.setText(QtGui.QApplication.translate("Form", "配速", None, QtGui.QApplication.UnicodeUTF8))
        self.pace.setChecked(True)
        self.pace.setObjectName(_fromUtf8("pace"))
        self.progressBar = QtGui.QProgressBar(Form)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(250, 190, 118, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.progressBar.hide()
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(510, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Form", "总距离", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(500, 181, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Form", "单圈距离", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.distance = QtGui.QLineEdit(Form)
        self.distance.setGeometry(QtCore.QRect(580, 140, 51, 20))
        self.distance.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.distance.setAlignment(QtCore.Qt.AlignCenter)
        self.distance.setObjectName(_fromUtf8("distance"))
        self.around = QtGui.QLineEdit(Form)
        self.around.setGeometry(QtCore.QRect(580, 180, 51, 20))
        self.around.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.around.setAlignment(QtCore.Qt.AlignCenter)
        self.around.setObjectName(_fromUtf8("around"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(640, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Form", "km", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(640, 180, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Form", "km", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

