# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swim_ui.ui'
#
# Created: Thu Dec 28 10:39:16 2017
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(583, 442)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        #weloop logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/weloop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        Form.setMinimumSize(QtCore.QSize(583, 442))
        Form.setMaximumSize(QtCore.QSize(583, 442))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 0, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Form", "游泳数据设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.start_time_2 = QtGui.QLabel(Form)
        self.start_time_2.setGeometry(QtCore.QRect(40, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_2.setFont(font)
        self.start_time_2.setText(QtGui.QApplication.translate("Form", "开始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_2.setObjectName(_fromUtf8("start_time_2"))
        self.start_time = QtGui.QDateTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(120, 60, 194, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time.setFont(font)
        self.start_time.setDate(QtCore.QDate(2017, 12, 13))
        self.start_time.setTime(QtCore.QTime(10, 0, 0))
        self.start_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.start_time.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.start_time.setMinimumTime(QtCore.QTime(10, 0, 0))
        self.start_time.setObjectName(_fromUtf8("start_time"))
        self.sport_time_2 = QtGui.QLabel(Form)
        self.sport_time_2.setGeometry(QtCore.QRect(200, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.sport_time_2.setFont(font)
        self.sport_time_2.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_2.setObjectName(_fromUtf8("sport_time_2"))
        self.sport_time_set = QtGui.QLineEdit(Form)
        self.sport_time_set.setGeometry(QtCore.QRect(120, 100, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_set.setFont(font)
        self.sport_time_set.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_set.setAlignment(QtCore.Qt.AlignCenter)
        self.sport_time_set.setObjectName(_fromUtf8("sport_time_set"))
        self.sport_time = QtGui.QLabel(Form)
        self.sport_time.setGeometry(QtCore.QRect(40, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time.setFont(font)
        self.sport_time.setText(QtGui.QApplication.translate("Form", "运动时长", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time.setObjectName(_fromUtf8("sport_time"))
        self.sport_time_3 = QtGui.QLabel(Form)
        self.sport_time_3.setGeometry(QtCore.QRect(260, 240, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_3.setFont(font)
        self.sport_time_3.setText(QtGui.QApplication.translate("Form", "卡路里", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_3.setObjectName(_fromUtf8("sport_time_3"))
        self.sport_time_4 = QtGui.QLabel(Form)
        self.sport_time_4.setGeometry(QtCore.QRect(270, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_4.setFont(font)
        self.sport_time_4.setText(QtGui.QApplication.translate("Form", "配速", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_4.setObjectName(_fromUtf8("sport_time_4"))
        self.sport_time_5 = QtGui.QLabel(Form)
        self.sport_time_5.setGeometry(QtCore.QRect(60, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_5.setFont(font)
        self.sport_time_5.setText(QtGui.QApplication.translate("Form", "划水次数", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_5.setObjectName(_fromUtf8("sport_time_5"))
        self.sport_time_6 = QtGui.QLabel(Form)
        self.sport_time_6.setGeometry(QtCore.QRect(270, 140, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_6.setFont(font)
        self.sport_time_6.setText(QtGui.QApplication.translate("Form", "泳姿", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_6.setObjectName(_fromUtf8("sport_time_6"))
        self.sport_time_7 = QtGui.QLabel(Form)
        self.sport_time_7.setGeometry(QtCore.QRect(60, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_7.setFont(font)
        self.sport_time_7.setText(QtGui.QApplication.translate("Form", "泳池长度", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_7.setObjectName(_fromUtf8("sport_time_7"))
        self.sport_time_8 = QtGui.QLabel(Form)
        self.sport_time_8.setGeometry(QtCore.QRect(80, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_8.setFont(font)
        self.sport_time_8.setText(QtGui.QApplication.translate("Form", "圈数", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_8.setObjectName(_fromUtf8("sport_time_8"))
        self.poor_len = QtGui.QLineEdit(Form)
        self.poor_len.setGeometry(QtCore.QRect(120, 140, 51, 20))
        self.poor_len.setText(QtGui.QApplication.translate("Form", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.poor_len.setAlignment(QtCore.Qt.AlignCenter)
        self.poor_len.setObjectName(_fromUtf8("poor_len"))
        self.lap_count = QtGui.QLineEdit(Form)
        self.lap_count.setGeometry(QtCore.QRect(120, 190, 51, 20))
        self.lap_count.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.lap_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_count.setObjectName(_fromUtf8("lap_count"))
        self.stroke_count = QtGui.QLineEdit(Form)
        self.stroke_count.setGeometry(QtCore.QRect(120, 240, 51, 20))
        self.stroke_count.setText(QtGui.QApplication.translate("Form", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.stroke_count.setAlignment(QtCore.Qt.AlignCenter)
        self.stroke_count.setObjectName(_fromUtf8("stroke_count"))
        self.swim_style = QtGui.QLineEdit(Form)
        self.swim_style.setGeometry(QtCore.QRect(310, 140, 51, 20))
        self.swim_style.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.swim_style.setAlignment(QtCore.Qt.AlignCenter)
        self.swim_style.setObjectName(_fromUtf8("swim_style"))
        self.pace = QtGui.QLineEdit(Form)
        self.pace.setGeometry(QtCore.QRect(310, 190, 51, 20))
        self.pace.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pace.setAlignment(QtCore.Qt.AlignCenter)
        self.pace.setObjectName(_fromUtf8("pace"))
        self.kcal = QtGui.QLineEdit(Form)
        self.kcal.setGeometry(QtCore.QRect(310, 240, 51, 20))
        self.kcal.setText(QtGui.QApplication.translate("Form", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.kcal.setAlignment(QtCore.Qt.AlignCenter)
        self.kcal.setObjectName(_fromUtf8("kcal"))
        self.start_time_3 = QtGui.QLabel(Form)
        self.start_time_3.setGeometry(QtCore.QRect(350, 60, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_3.setFont(font)
        self.start_time_3.setText(QtGui.QApplication.translate("Form", "时区", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_3.setObjectName(_fromUtf8("start_time_3"))
        self.time_zone = QtGui.QLineEdit(Form)
        self.time_zone.setGeometry(QtCore.QRect(380, 60, 41, 20))
        self.time_zone.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.time_zone.setObjectName(_fromUtf8("time_zone"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 140, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(370, 240, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Form", "kcal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(370, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Form", "min/100m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(380, 130, 131, 41))
        self.label_5.setText(QtGui.QApplication.translate("Form", "1:自由泳-2:蛙泳\n"
"3:仰泳-4:混合泳", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.swim_data_show = QtGui.QTextEdit(Form)
        self.swim_data_show.setGeometry(QtCore.QRect(0, 330, 581, 111))
        self.swim_data_show.setObjectName(_fromUtf8("swim_data_show"))
        self.commit = QtGui.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(180, 290, 61, 41))
        self.commit.setText(QtGui.QApplication.translate("Form", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.commit.setObjectName(_fromUtf8("commit"))
        self.verify = QtGui.QPushButton(Form)
        self.verify.setGeometry(QtCore.QRect(260, 290, 61, 41))
        self.verify.setText(QtGui.QApplication.translate("Form", "验证", None, QtGui.QApplication.UnicodeUTF8))
        self.verify.setObjectName(_fromUtf8("verify"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

