# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daily_data_ui.ui'
#
# Created: Wed Dec 27 14:20:25 2017
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(656, 495)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        Form.setFont(font)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        Form.setMinimumSize(QtCore.QSize(656, 495))
        Form.setMaximumSize(QtCore.QSize(656, 495))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())

        # weloop logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/weloop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label.setStyleSheet("color:white")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Form", "数据格式设定", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(13, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_2.setStyleSheet("color:white")
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Form", "开始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(290, 70, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_5.setStyleSheet("color:white")
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("Form", "时区", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.time_zone = QtGui.QLineEdit(Form)
        self.time_zone.setGeometry(QtCore.QRect(330, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.time_zone.setFont(font)
        self.time_zone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_zone.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.time_zone.setObjectName(_fromUtf8("time_zone"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(280, 360, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_10.setStyleSheet("color:white")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("Form", "数据展示", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.data_show = QtGui.QTextEdit(Form)
        self.data_show.setGeometry(QtCore.QRect(0, 390, 651, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.data_show.setFont(font)
        self.data_show.setObjectName(_fromUtf8("data_show"))
        self.commit = QtGui.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(220, 320, 75, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.commit.setFont(font)
        self.commit.setText(QtGui.QApplication.translate("Form", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.commit.setObjectName(_fromUtf8("commit"))
        self.verity = QtGui.QPushButton(Form)
        self.verity.setGeometry(QtCore.QRect(330, 320, 75, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.verity.setFont(font)
        self.verity.setText(QtGui.QApplication.translate("Form", "验证", None, QtGui.QApplication.UnicodeUTF8))
        self.verity.setObjectName(_fromUtf8("verity"))
        self.start_time = QtGui.QDateTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(80, 70, 194, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.start_time.setFont(font)
        self.start_time.setDate(QtCore.QDate(2017, 12, 13))
        self.start_time.setTime(QtCore.QTime(10, 0, 0))
        self.start_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.start_time.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.start_time.setMinimumTime(QtCore.QTime(10, 0, 0))
        self.start_time.setObjectName(_fromUtf8("start_time"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(390, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_3.setStyleSheet("color:white")
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Form", "结束时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.end_time = QtGui.QLineEdit(Form)
        self.end_time.setGeometry(QtCore.QRect(450, 70, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.end_time.setFont(font)
        self.end_time.setText(QtGui.QApplication.translate("Form", "2017/12/13 00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.end_time.setObjectName(_fromUtf8("end_time"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 131, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_4.setStyleSheet("color:white")
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Form", "运动状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_6.setStyleSheet("color:white")
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Form", "运动状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_7.setStyleSheet("color:white")
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("Form", "运动状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_8.setStyleSheet("color:white")
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("Form", "运动状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.status_1 = QtGui.QComboBox(Form)
        self.status_1.setGeometry(QtCore.QRect(80, 130, 69, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.status_1.setFont(font)
        self.status_1.setObjectName(_fromUtf8("status_1"))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(0, QtGui.QApplication.translate("Form", "请选择", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(1, QtGui.QApplication.translate("Form", "摘下", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(2, QtGui.QApplication.translate("Form", "睡眠", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(3, QtGui.QApplication.translate("Form", "散步", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(4, QtGui.QApplication.translate("Form", "健走", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(5, QtGui.QApplication.translate("Form", "低运动量", None, QtGui.QApplication.UnicodeUTF8))
        self.status_1.addItem(_fromUtf8(""))
        self.status_1.setItemText(6, QtGui.QApplication.translate("Form", "运动", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2 = QtGui.QComboBox(Form)
        self.status_2.setGeometry(QtCore.QRect(80, 170, 69, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.status_2.setFont(font)
        self.status_2.setObjectName(_fromUtf8("status_2"))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(0, QtGui.QApplication.translate("Form", "请选择", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(1, QtGui.QApplication.translate("Form", "摘下", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(2, QtGui.QApplication.translate("Form", "睡眠", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(3, QtGui.QApplication.translate("Form", "散步", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(4, QtGui.QApplication.translate("Form", "健走", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(5, QtGui.QApplication.translate("Form", "低运动量", None, QtGui.QApplication.UnicodeUTF8))
        self.status_2.addItem(_fromUtf8(""))
        self.status_2.setItemText(6, QtGui.QApplication.translate("Form", "运动", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3 = QtGui.QComboBox(Form)
        self.status_3.setGeometry(QtCore.QRect(80, 220, 71, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.status_3.setFont(font)

        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(0, QtGui.QApplication.translate("Form", "请选择", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(1, QtGui.QApplication.translate("Form", "摘下", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(2, QtGui.QApplication.translate("Form", "睡眠", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(3, QtGui.QApplication.translate("Form", "散步", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(4, QtGui.QApplication.translate("Form", "健走", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(5, QtGui.QApplication.translate("Form", "低运动量", None, QtGui.QApplication.UnicodeUTF8))
        self.status_3.addItem(_fromUtf8(""))
        self.status_3.setItemText(6, QtGui.QApplication.translate("Form", "运动", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4 = QtGui.QComboBox(Form)
        self.status_4.setGeometry(QtCore.QRect(80, 270, 69, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.status_4.setFont(font)

        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(0, QtGui.QApplication.translate("Form", "请选择", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(1, QtGui.QApplication.translate("Form", "摘下", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(2, QtGui.QApplication.translate("Form", "睡眠", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(3, QtGui.QApplication.translate("Form", "散步", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(4, QtGui.QApplication.translate("Form", "健走", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(5, QtGui.QApplication.translate("Form", "低运动量", None, QtGui.QApplication.UnicodeUTF8))
        self.status_4.addItem(_fromUtf8(""))
        self.status_4.setItemText(6, QtGui.QApplication.translate("Form", "运动", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(180, 130, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_9.setStyleSheet("color:white")
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("Form", "持续时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(180, 270, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_11.setStyleSheet("color:white")
        self.label_11.setFont(font)
        self.label_11.setText(QtGui.QApplication.translate("Form", "持续时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(180, 170, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_12.setStyleSheet("color:white")
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("Form", "持续时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(180, 220, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_13.setStyleSheet("color:white")
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("Form", "持续时间", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.status_time1 = QtGui.QLineEdit(Form)
        self.status_time1.setGeometry(QtCore.QRect(240, 130, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))

        self.status_time1.setFont(font)
        self.status_time1.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.status_time1.setAlignment(QtCore.Qt.AlignCenter)
        self.status_time1.setObjectName(_fromUtf8("status_time1"))
        self.status_time2 = QtGui.QLineEdit(Form)
        self.status_time2.setGeometry(QtCore.QRect(240, 170, 61, 20))
        font = QtGui.QFont()

        self.status_time2.setFont(font)
        self.status_time2.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.status_time2.setAlignment(QtCore.Qt.AlignCenter)
        self.status_time2.setObjectName(_fromUtf8("status_time2"))
        self.status_time3 = QtGui.QLineEdit(Form)
        self.status_time3.setGeometry(QtCore.QRect(240, 220, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.status_time3.setFont(font)
        self.status_time3.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.status_time3.setAlignment(QtCore.Qt.AlignCenter)
        self.status_time3.setObjectName(_fromUtf8("status_time3"))
        self.status_time4 = QtGui.QLineEdit(Form)
        self.status_time4.setGeometry(QtCore.QRect(240, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.status_time4.setFont(font)
        self.status_time4.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.status_time4.setAlignment(QtCore.Qt.AlignCenter)
        self.status_time4.setObjectName(_fromUtf8("status_time4"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(310, 130, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_14.setStyleSheet("color:white")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(310, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_15.setStyleSheet("color:white")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(310, 220, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_16.setStyleSheet("color:white")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(310, 270, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_17.setStyleSheet("color:white")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.energe_2 = QtGui.QLineEdit(Form)
        self.energe_2.setGeometry(QtCore.QRect(400, 170, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.energe_2.setFont(font)
        self.energe_2.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.energe_2.setAlignment(QtCore.Qt.AlignCenter)
        self.energe_2.setObjectName(_fromUtf8("energe_2"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(360, 170, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_18.setStyleSheet("color:white")
        self.label_18.setFont(font)
        self.label_18.setText(QtGui.QApplication.translate("Form", "能量值", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.energe_1 = QtGui.QLineEdit(Form)
        self.energe_1.setGeometry(QtCore.QRect(400, 130, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.energe_1.setFont(font)
        self.energe_1.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.energe_1.setAlignment(QtCore.Qt.AlignCenter)
        self.energe_1.setObjectName(_fromUtf8("energe_1"))
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(360, 130, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_19.setStyleSheet("color:white")
        self.label_19.setFont(font)
        self.label_19.setText(QtGui.QApplication.translate("Form", "能量值", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(360, 270, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_20.setStyleSheet("color:white")
        self.label_20.setFont(font)
        self.label_20.setText(QtGui.QApplication.translate("Form", "能量值", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.energe_3 = QtGui.QLineEdit(Form)
        self.energe_3.setGeometry(QtCore.QRect(400, 220, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.energe_3.setFont(font)
        self.energe_3.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.energe_3.setAlignment(QtCore.Qt.AlignCenter)
        self.energe_3.setObjectName(_fromUtf8("energe_3"))
        self.label_21 = QtGui.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(360, 220, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_21.setStyleSheet("color:white")
        self.label_21.setFont(font)
        self.label_21.setText(QtGui.QApplication.translate("Form", "能量值", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.energe_4 = QtGui.QLineEdit(Form)
        self.energe_4.setGeometry(QtCore.QRect(400, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.energe_4.setFont(font)
        self.energe_4.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.energe_4.setAlignment(QtCore.Qt.AlignCenter)
        self.energe_4.setObjectName(_fromUtf8("energe_4"))
        self.step_2 = QtGui.QLineEdit(Form)
        self.step_2.setGeometry(QtCore.QRect(530, 170, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.step_2.setFont(font)
        self.step_2.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.step_2.setAlignment(QtCore.Qt.AlignCenter)
        self.step_2.setObjectName(_fromUtf8("step_2"))
        self.label_22 = QtGui.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(490, 170, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_22.setStyleSheet("color:white")
        self.label_22.setFont(font)
        self.label_22.setText(QtGui.QApplication.translate("Form", "步数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.step_1 = QtGui.QLineEdit(Form)
        self.step_1.setGeometry(QtCore.QRect(530, 130, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.step_1.setFont(font)
        self.step_1.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.step_1.setAlignment(QtCore.Qt.AlignCenter)
        self.step_1.setObjectName(_fromUtf8("step_1"))
        self.label_23 = QtGui.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(490, 130, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_23.setStyleSheet("color:white")
        self.label_23.setFont(font)
        self.label_23.setText(QtGui.QApplication.translate("Form", "步数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(490, 270, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_24.setStyleSheet("color:white")
        self.label_24.setFont(font)
        self.label_24.setText(QtGui.QApplication.translate("Form", "步数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.step_3 = QtGui.QLineEdit(Form)
        self.step_3.setGeometry(QtCore.QRect(530, 220, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.step_3.setFont(font)
        self.step_3.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.step_3.setAlignment(QtCore.Qt.AlignCenter)
        self.step_3.setObjectName(_fromUtf8("step_3"))
        self.label_25 = QtGui.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(490, 220, 54, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_25.setStyleSheet("color:white")
        self.label_25.setFont(font)
        self.label_25.setText(QtGui.QApplication.translate("Form", "步数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.step_4 = QtGui.QLineEdit(Form)
        self.step_4.setGeometry(QtCore.QRect(530, 270, 61, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.step_4.setFont(font)
        self.step_4.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.step_4.setAlignment(QtCore.Qt.AlignCenter)
        self.step_4.setObjectName(_fromUtf8("step_4"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

