# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coros_run_set.ui'
#
# Created: Thu Jan 11 14:36:25 2018
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(667, 387)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        # coros logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/coros_Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        self.time_zone_2 = QtGui.QLabel(Form)
        self.time_zone_2.setGeometry(QtCore.QRect(310, 60, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.time_zone_2.setFont(font)
        self.time_zone_2.setText(QtGui.QApplication.translate("Form", "时区", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone_2.setObjectName(_fromUtf8("time_zone_2"))
        self.time_zone = QtGui.QLineEdit(Form)
        self.time_zone.setGeometry(QtCore.QRect(350, 60, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.time_zone.setFont(font)
        self.time_zone.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_zone.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.time_zone.setObjectName(_fromUtf8("time_zone"))
        self.end_time = QtGui.QLineEdit(Form)
        self.end_time.setGeometry(QtCore.QRect(470, 60, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.end_time.setFont(font)
        self.end_time.setText(QtGui.QApplication.translate("Form", "2017/12/13 00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.end_time.setAlignment(QtCore.Qt.AlignCenter)
        self.end_time.setObjectName(_fromUtf8("end_time"))
        self.start_time_2 = QtGui.QLabel(Form)
        self.start_time_2.setGeometry(QtCore.QRect(33, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_2.setFont(font)
        self.start_time_2.setText(QtGui.QApplication.translate("Form", "开始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_2.setObjectName(_fromUtf8("start_time_2"))
        self.start_time = QtGui.QDateTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(100, 60, 194, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time.setFont(font)
        self.start_time.setDate(QtCore.QDate(2017, 12, 13))
        self.start_time.setTime(QtCore.QTime(10, 0, 0))
        self.start_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.start_time.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.start_time.setMinimumTime(QtCore.QTime(10, 0, 0))
        self.start_time.setObjectName(_fromUtf8("start_time"))
        self.title = QtGui.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(260, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setText(QtGui.QApplication.translate("Form", "数据格式设定", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setObjectName(_fromUtf8("title"))
        self.end_time_2 = QtGui.QLabel(Form)
        self.end_time_2.setGeometry(QtCore.QRect(410, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.end_time_2.setFont(font)
        self.end_time_2.setText(QtGui.QApplication.translate("Form", "结束时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.end_time_2.setObjectName(_fromUtf8("end_time_2"))
        self.locus_box = QtGui.QComboBox(Form)
        self.locus_box.setGeometry(QtCore.QRect(130, 120, 69, 22))
        self.locus_box.setObjectName(_fromUtf8("locus_box"))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(0, QtGui.QApplication.translate("Form", "东莞", None, QtGui.QApplication.UnicodeUTF8))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(1, QtGui.QApplication.translate("Form", "深圳", None, QtGui.QApplication.UnicodeUTF8))
        self.locus_box.addItem(_fromUtf8(""))
        self.locus_box.setItemText(2, QtGui.QApplication.translate("Form", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.locus = QtGui.QLabel(Form)
        self.locus.setGeometry(QtCore.QRect(70, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.locus.setFont(font)
        self.locus.setText(QtGui.QApplication.translate("Form", "轨迹区域", None, QtGui.QApplication.UnicodeUTF8))
        self.locus.setObjectName(_fromUtf8("locus"))
        self.sport_time = QtGui.QLabel(Form)
        self.sport_time.setGeometry(QtCore.QRect(70, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time.setFont(font)
        self.sport_time.setText(QtGui.QApplication.translate("Form", "运动时长", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time.setObjectName(_fromUtf8("sport_time"))
        self.sport_time_set = QtGui.QLineEdit(Form)
        self.sport_time_set.setGeometry(QtCore.QRect(130, 190, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_set.setFont(font)
        self.sport_time_set.setText(QtGui.QApplication.translate("Form", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_set.setAlignment(QtCore.Qt.AlignCenter)
        self.sport_time_set.setObjectName(_fromUtf8("sport_time_set"))
        self.sport_time_2 = QtGui.QLabel(Form)
        self.sport_time_2.setGeometry(QtCore.QRect(210, 190, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.sport_time_2.setFont(font)
        self.sport_time_2.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_2.setObjectName(_fromUtf8("sport_time_2"))
        self.commit = QtGui.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(70, 310, 61, 31))
        self.commit.setText(QtGui.QApplication.translate("Form", "确认", None, QtGui.QApplication.UnicodeUTF8))
        self.commit.setObjectName(_fromUtf8("commit"))
        self.data_choice = QtGui.QLabel(Form)
        self.data_choice.setGeometry(QtCore.QRect(430, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.data_choice.setFont(font)
        self.data_choice.setText(QtGui.QApplication.translate("Form", " 数据设置", None, QtGui.QApplication.UnicodeUTF8))
        self.data_choice.setObjectName(_fromUtf8("data_choice"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(500, 141, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Form", "单圈距离", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.around = QtGui.QLineEdit(Form)
        self.around.setGeometry(QtCore.QRect(560, 140, 51, 20))
        self.around.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.around.setAlignment(QtCore.Qt.AlignCenter)
        self.around.setObjectName(_fromUtf8("around"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(620, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Form", "km", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(430, 140, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("Form", "km", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(320, 141, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Form", "总距离", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.distance = QtGui.QLineEdit(Form)
        self.distance.setGeometry(QtCore.QRect(370, 140, 51, 20))
        self.distance.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.distance.setAlignment(QtCore.Qt.AlignCenter)
        self.distance.setObjectName(_fromUtf8("distance"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 191, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Form", "总卡路里", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.kcal = QtGui.QLineEdit(Form)
        self.kcal.setGeometry(QtCore.QRect(370, 190, 51, 20))
        self.kcal.setText(QtGui.QApplication.translate("Form", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.kcal.setAlignment(QtCore.Qt.AlignCenter)
        self.kcal.setObjectName(_fromUtf8("kcal"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(430, 190, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Form", "kcal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(500, 191, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("Form", "平均心率", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.heart = QtGui.QLineEdit(Form)
        self.heart.setGeometry(QtCore.QRect(560, 190, 51, 20))
        self.heart.setText(QtGui.QApplication.translate("Form", "130", None, QtGui.QApplication.UnicodeUTF8))
        self.heart.setAlignment(QtCore.Qt.AlignCenter)
        self.heart.setObjectName(_fromUtf8("heart"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(500, 230, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("Form", "总下降", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.decline = QtGui.QLineEdit(Form)
        self.decline.setGeometry(QtCore.QRect(560, 229, 51, 20))
        self.decline.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.decline.setAlignment(QtCore.Qt.AlignCenter)
        self.decline.setObjectName(_fromUtf8("decline"))
        self.elevation = QtGui.QLineEdit(Form)
        self.elevation.setGeometry(QtCore.QRect(370, 229, 51, 20))
        self.elevation.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.elevation.setAlignment(QtCore.Qt.AlignCenter)
        self.elevation.setObjectName(_fromUtf8("elevation"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(310, 230, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("Form", "总上升", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(430, 230, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(620, 230, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setText(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.most_step = QtGui.QLineEdit(Form)
        self.most_step.setGeometry(QtCore.QRect(370, 269, 51, 20))
        self.most_step.setText(QtGui.QApplication.translate("Form", "180", None, QtGui.QApplication.UnicodeUTF8))
        self.most_step.setAlignment(QtCore.Qt.AlignCenter)
        self.most_step.setObjectName(_fromUtf8("most_step"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(310, 270, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("Form", "最大步频", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.most_heart = QtGui.QLineEdit(Form)
        self.most_heart.setGeometry(QtCore.QRect(560, 269, 51, 20))
        self.most_heart.setText(QtGui.QApplication.translate("Form", "170", None, QtGui.QApplication.UnicodeUTF8))
        self.most_heart.setAlignment(QtCore.Qt.AlignCenter)
        self.most_heart.setObjectName(_fromUtf8("most_heart"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(500, 270, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_15.setFont(font)
        self.label_15.setText(QtGui.QApplication.translate("Form", "最大心率", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.most_pace = QtGui.QLineEdit(Form)
        self.most_pace.setGeometry(QtCore.QRect(370, 310, 51, 20))
        self.most_pace.setText(QtGui.QApplication.translate("Form", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.most_pace.setAlignment(QtCore.Qt.AlignCenter)
        self.most_pace.setObjectName(_fromUtf8("most_pace"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(500, 311, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("Form", "平均配速", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(310, 311, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.label_14.setFont(font)
        self.label_14.setText(QtGui.QApplication.translate("Form", "最大配速", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.avg_pace = QtGui.QLineEdit(Form)
        self.avg_pace.setGeometry(QtCore.QRect(560, 310, 51, 20))
        self.avg_pace.setText(QtGui.QApplication.translate("Form", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_pace.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_pace.setObjectName(_fromUtf8("avg_pace"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(430, 310, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("Form", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(620, 310, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setText(QtGui.QApplication.translate("Form", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.finish = QtGui.QPushButton(Form)
        self.finish.setGeometry(QtCore.QRect(150, 310, 61, 31))
        self.finish.setText(QtGui.QApplication.translate("Form", "完成", None, QtGui.QApplication.UnicodeUTF8))
        self.finish.setObjectName(_fromUtf8("finish"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

