# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coros_pool_swim_set.ui'
#
# Created: Thu Jan 11 14:43:03 2018
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(524, 476)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        # coros logo设计
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/coros_Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("Form", "游泳数据设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.start_time_2 = QtGui.QLabel(Form)
        self.start_time_2.setGeometry(QtCore.QRect(60, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_2.setFont(font)
        self.start_time_2.setText(QtGui.QApplication.translate("Form", "开始时间：", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_2.setObjectName(_fromUtf8("start_time_2"))
        self.start_time = QtGui.QDateTimeEdit(Form)
        self.start_time.setGeometry(QtCore.QRect(120, 60, 194, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time.setFont(font)
        self.start_time.setDate(QtCore.QDate(2017, 12, 13))
        self.start_time.setTime(QtCore.QTime(10, 0, 0))
        self.start_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.start_time.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.start_time.setMinimumTime(QtCore.QTime(10, 0, 0))
        self.start_time.setObjectName(_fromUtf8("start_time"))
        self.sport_time_2 = QtGui.QLabel(Form)
        self.sport_time_2.setGeometry(QtCore.QRect(200, 100, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(12)
        self.sport_time_2.setFont(font)
        self.sport_time_2.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_2.setObjectName(_fromUtf8("sport_time_2"))
        self.sport_time_set = QtGui.QLineEdit(Form)
        self.sport_time_set.setGeometry(QtCore.QRect(120, 100, 71, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_set.setFont(font)
        self.sport_time_set.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_set.setAlignment(QtCore.Qt.AlignCenter)
        self.sport_time_set.setObjectName(_fromUtf8("sport_time_set"))
        self.sport_time = QtGui.QLabel(Form)
        self.sport_time.setGeometry(QtCore.QRect(60, 100, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time.setFont(font)
        self.sport_time.setText(QtGui.QApplication.translate("Form", "运动时长", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time.setObjectName(_fromUtf8("sport_time"))
        self.sport_time_3 = QtGui.QLabel(Form)
        self.sport_time_3.setGeometry(QtCore.QRect(70, 280, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_3.setFont(font)
        self.sport_time_3.setText(QtGui.QApplication.translate("Form", "卡路里", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_3.setObjectName(_fromUtf8("sport_time_3"))
        self.sport_time_4 = QtGui.QLabel(Form)
        self.sport_time_4.setGeometry(QtCore.QRect(270, 100, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_4.setFont(font)
        self.sport_time_4.setText(QtGui.QApplication.translate("Form", "最大配速", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_4.setObjectName(_fromUtf8("sport_time_4"))
        self.sport_time_5 = QtGui.QLabel(Form)
        self.sport_time_5.setGeometry(QtCore.QRect(50, 250, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_5.setFont(font)
        self.sport_time_5.setText(QtGui.QApplication.translate("Form", "总划水次数", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_5.setObjectName(_fromUtf8("sport_time_5"))
        self.sport_time_6 = QtGui.QLabel(Form)
        self.sport_time_6.setGeometry(QtCore.QRect(80, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_6.setFont(font)
        self.sport_time_6.setText(QtGui.QApplication.translate("Form", "泳姿", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_6.setObjectName(_fromUtf8("sport_time_6"))
        self.sport_time_7 = QtGui.QLabel(Form)
        self.sport_time_7.setGeometry(QtCore.QRect(60, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_7.setFont(font)
        self.sport_time_7.setText(QtGui.QApplication.translate("Form", "单圈距离", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_7.setObjectName(_fromUtf8("sport_time_7"))
        self.sport_time_8 = QtGui.QLabel(Form)
        self.sport_time_8.setGeometry(QtCore.QRect(80, 160, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_8.setFont(font)
        self.sport_time_8.setText(QtGui.QApplication.translate("Form", "圈数", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_8.setObjectName(_fromUtf8("sport_time_8"))
        self.dis_len = QtGui.QLineEdit(Form)
        self.dis_len.setGeometry(QtCore.QRect(120, 130, 51, 20))
        self.dis_len.setText(QtGui.QApplication.translate("Form", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.dis_len.setAlignment(QtCore.Qt.AlignCenter)
        self.dis_len.setObjectName(_fromUtf8("dis_len"))
        self.lap_count = QtGui.QLineEdit(Form)
        self.lap_count.setGeometry(QtCore.QRect(120, 160, 51, 20))
        self.lap_count.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.lap_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lap_count.setObjectName(_fromUtf8("lap_count"))
        self.stroke_count = QtGui.QLineEdit(Form)
        self.stroke_count.setGeometry(QtCore.QRect(120, 250, 51, 20))
        self.stroke_count.setText(QtGui.QApplication.translate("Form", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.stroke_count.setAlignment(QtCore.Qt.AlignCenter)
        self.stroke_count.setObjectName(_fromUtf8("stroke_count"))
        self.swim_style = QtGui.QLineEdit(Form)
        self.swim_style.setGeometry(QtCore.QRect(120, 190, 51, 20))
        self.swim_style.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.swim_style.setAlignment(QtCore.Qt.AlignCenter)
        self.swim_style.setObjectName(_fromUtf8("swim_style"))
        self.most_pace = QtGui.QLineEdit(Form)
        self.most_pace.setGeometry(QtCore.QRect(340, 100, 51, 20))
        self.most_pace.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.most_pace.setAlignment(QtCore.Qt.AlignCenter)
        self.most_pace.setObjectName(_fromUtf8("most_pace"))
        self.kcal = QtGui.QLineEdit(Form)
        self.kcal.setGeometry(QtCore.QRect(120, 280, 51, 20))
        self.kcal.setText(QtGui.QApplication.translate("Form", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.kcal.setAlignment(QtCore.Qt.AlignCenter)
        self.kcal.setObjectName(_fromUtf8("kcal"))
        self.start_time_3 = QtGui.QLabel(Form)
        self.start_time_3.setGeometry(QtCore.QRect(350, 60, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.start_time_3.setFont(font)
        self.start_time_3.setText(QtGui.QApplication.translate("Form", "时区", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_3.setObjectName(_fromUtf8("start_time_3"))
        self.time_zone = QtGui.QLineEdit(Form)
        self.time_zone.setGeometry(QtCore.QRect(380, 60, 41, 20))
        self.time_zone.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.time_zone.setAlignment(QtCore.Qt.AlignCenter)
        self.time_zone.setObjectName(_fromUtf8("time_zone"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 130, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 280, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("Form", "kcal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(400, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("Form", "min/100m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(80, 210, 121, 41))
        self.label_5.setText(QtGui.QApplication.translate("Form", "1:自由泳-2:蛙泳\n"
"3:仰泳-4:混合泳", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.commit = QtGui.QPushButton(Form)
        self.commit.setGeometry(QtCore.QRect(200, 300, 71, 31))
        self.commit.setText(QtGui.QApplication.translate("Form", "确定", None, QtGui.QApplication.UnicodeUTF8))
        self.commit.setObjectName(_fromUtf8("commit"))

        #account输入框
        self.account = QtGui.QLineEdit(Form)
        self.account.setGeometry(QtCore.QRect(90, 310, 80, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.account.setFont(font)
        self.account.setText(QtGui.QApplication.translate("Form", "", None, QtGui.QApplication.UnicodeUTF8))
        self.account.setAlignment(QtCore.Qt.AlignCenter)
        self.account.setObjectName(_fromUtf8("account"))
        self.account_1 = QtGui.QLabel(Form)
        self.account_1.setGeometry(QtCore.QRect(30, 310, 60, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.account_1.setFont(font)
        self.account_1.setText(QtGui.QApplication.translate("Form", "帐号输入:", None, QtGui.QApplication.UnicodeUTF8))
        self.account_1.setObjectName(_fromUtf8("account_1"))

        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(400, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("Form", "min/100m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sport_time_9 = QtGui.QLabel(Form)
        self.sport_time_9.setGeometry(QtCore.QRect(270, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_9.setFont(font)
        self.sport_time_9.setText(QtGui.QApplication.translate("Form", "平均配速", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_9.setObjectName(_fromUtf8("sport_time_9"))
        self.avg_pace = QtGui.QLineEdit(Form)
        self.avg_pace.setGeometry(QtCore.QRect(340, 140, 51, 20))
        self.avg_pace.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_pace.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_pace.setObjectName(_fromUtf8("avg_pace"))
        self.avg_str_rate = QtGui.QLineEdit(Form)
        self.avg_str_rate.setGeometry(QtCore.QRect(340, 220, 51, 20))
        self.avg_str_rate.setText(QtGui.QApplication.translate("Form", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_str_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_str_rate.setObjectName(_fromUtf8("avg_str_rate"))
        self.sport_time_10 = QtGui.QLabel(Form)
        self.sport_time_10.setGeometry(QtCore.QRect(260, 220, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_10.setFont(font)
        self.sport_time_10.setText(QtGui.QApplication.translate("Form", "平均划水率", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_10.setObjectName(_fromUtf8("sport_time_10"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(400, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("Form", "str/min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sport_time_11 = QtGui.QLabel(Form)
        self.sport_time_11.setGeometry(QtCore.QRect(260, 180, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_11.setFont(font)
        self.sport_time_11.setText(QtGui.QApplication.translate("Form", "最大划水率", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_11.setObjectName(_fromUtf8("sport_time_11"))
        self.most_str_rate = QtGui.QLineEdit(Form)
        self.most_str_rate.setGeometry(QtCore.QRect(340, 180, 51, 20))
        self.most_str_rate.setText(QtGui.QApplication.translate("Form", "40", None, QtGui.QApplication.UnicodeUTF8))
        self.most_str_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.most_str_rate.setObjectName(_fromUtf8("most_str_rate"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(400, 220, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("Form", "str/min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.most_swolf = QtGui.QLineEdit(Form)
        self.most_swolf.setGeometry(QtCore.QRect(340, 250, 51, 20))
        self.most_swolf.setText(QtGui.QApplication.translate("Form", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.most_swolf.setAlignment(QtCore.Qt.AlignCenter)
        self.most_swolf.setObjectName(_fromUtf8("most_swolf"))
        self.sport_time_12 = QtGui.QLabel(Form)
        self.sport_time_12.setGeometry(QtCore.QRect(270, 280, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_12.setFont(font)
        self.sport_time_12.setText(QtGui.QApplication.translate("Form", "平均swolf", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_12.setObjectName(_fromUtf8("sport_time_12"))
        self.sport_time_13 = QtGui.QLabel(Form)
        self.sport_time_13.setGeometry(QtCore.QRect(270, 250, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        self.sport_time_13.setFont(font)
        self.sport_time_13.setText(QtGui.QApplication.translate("Form", "最大swolf", None, QtGui.QApplication.UnicodeUTF8))
        self.sport_time_13.setObjectName(_fromUtf8("sport_time_13"))
        self.avg_swolf = QtGui.QLineEdit(Form)
        self.avg_swolf.setGeometry(QtCore.QRect(340, 280, 51, 20))
        self.avg_swolf.setText(QtGui.QApplication.translate("Form", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.avg_swolf.setAlignment(QtCore.Qt.AlignCenter)
        self.avg_swolf.setObjectName(_fromUtf8("avg_swolf"))
        self.data_set = QtGui.QTextEdit(Form)
        self.data_set.setGeometry(QtCore.QRect(3, 340, 521, 131))
        self.data_set.setObjectName(_fromUtf8("data_set"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

